---
title: Bits and Bytes
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Shreyas Srivastava
show_downloads: true
author: Shreyas Srivastava
url: https://shreyas88.github.io/
google_analytics: 
theme: jekyll-theme-hacker
